server:
  port: 80
spring:
  application:
    name: sysmanager-crud-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sysmanager_crud_project?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/sysmanager_crud_project?useTimezone=true&serverTimezone=America/Sao_Paulo
    user: root
    password: admin123